Page Title: coach

#Object Definitions
====================================================================================
button_Register             xpath                  (//button[@class='btn btn-default signin'])[1]
textbox_FirstName			xpath				   //input[@id='dwfrm_profile_customer_firstname']
textbox_LastName			xpath				   //input[@id='dwfrm_profile_customer_lastname']
textbox_eMailAddress		xpath				   //input[@id='dwfrm_profile_customer_email']
textbox_confirmEmail        xpath 				   //input[@id='dwfrm_profile_customer_emailconfirm']
textbox_password			xpath				   //input[@id='dwfrm_profile_login_password']
textbox_confirmPassword		xpath				   //input[@id='dwfrm_profile_login_passwordconfirm']
checkbox_SignMeIN			xpath				   //input[@id='dwfrm_profile_customer_addtoemaillist']
button_SignUp				xpath				   //button[@class='btn btn-default continue' and @name='dwfrm_profile_confirm']
textbox_addressField1		xpath				   //input[@id='dwfrm_profile_address_address1']
textbox_addressField2		xpath                  //input[@id='dwfrm_profile_address_address2']
textbox_postalCode			xpath				   //input[@id='dwfrm_profile_address_zip']
textbox_city				xpath 				   //input[@id='dwfrm_profile_address_city']
textbox_phone				xpath				   //input[@id='dwfrm_profile_address_phone']
button_Complete 			xpath				   //button[@class='apply-button btn' and contains(text(),"Complete")]
textMessage_Welcome			xpath 				   //p[@class='text-center welcome-massage']
page_heading                xpath                  //a[@title='COACH']/span
button_login_register       xpath                  //span[contains(text(),'Sign In/Register')]
login_button                xpath                  (//span[contains(text(),'Sign In')])[2]
username_field              xpath                  //input[contains(@id,'dwfrm_login_username')]
password_field              xpath                  //input[@id='dwfrm_login_password']
signin_button               xpath                  (//button[@class='btn btn-default signin'])[2]
signin_button2	            xpath                   //button[@class='btn checkout btn-default']
checkbox_remember		    xpath	   			   //*[contains(text(),'dwfrm_login_rememberme')]
linkText_Skip				xpath				   //a[contains(@class,'skip-button') and contains(text(),'SKIP')]
button_Save_Changes			xpath					(//button[@value="SAVE CHANGES"])[1]
textbox_current_password	xpath					#dwfrm_profile_login_currentpassword
textbox_new_password		xpath					#dwfrm_profile_login_newpassword
textbox_current_password_account_information_section	 xpath		(//input[@id='dwfrm_profile_login_currentpassword'])[1]
linkText_Address_Book 		xpath					//div[@id='secondary']//a[text()="Address Book"]
label_Address_Book			xpath					//div[@id='addresses']//h3[text()="ADDRESS BOOK"]
button_Add_New_Address		xpath					(//div[@id='addresses']//a[@title="ADD NEW"])[1]
linkText_Edit_Address		xpath					//div[@id='addresses']//a[contains(text(),'Edit')]
label_Message_after_Save_Address	xpath			//p[text()='Address has been saved successfully.']
button_Close_Address		xpath					//button[contains(text(),"Close")]
linkText_Saved_Credit_Cards	xpath					//div[@id='secondary']//a[text()="Saved Credit Cards"]
icon_Delete_Saved_Cards  	xpath					//div[@id='primary']//a[contains(@class,'button-text delete')]
button_Yes_Delete_Cards		xpath					//form[@id='creditcards_1']/button[contains(text(),"Yes")]
label_You_dont_have_Cards	xpath					//div[@id='primary']//h5[contains(text(),"You do not have a saved credit card.")]      
btn_add_new_credit_card		xpath 					//a[@title='Add New '] 
field_card_no				xpath					(//input[contains(@name,'dwfrm_paymentinstruments_creditcards_newcreditcard')])[2]
field_cvv_no				xpath					//input[contains(@id,'password_dwfrm_paymentinstruments')]
dropdown_card_month			xpath					//select[contains(@name,'newcreditcard_month')]
dropdown_card_year			xpath					//select[contains(@name,'newcreditcard_year')]
text_card_mnth				xpath					//option[@class="select-option" and @value="3"]
text_card_year				xpath					//option[@class="select-option" and @value="2018"]
btn_card_save				xpath					//button[@id='applyBtn']
window_card					xpath					//div[@class='modal-content']
window_card_close			xpath					//button[@class='icon-coach-close-black']
btn_card_close				xpath					//button[contains(@value,'Close')]
label_State					xpath					//span[text()="State"]
label_CreateAnAccount			xpath					(//h2[@class='section-header text-center'])[1]
label_RegisterNowToAccess		xpath					(//div[@class='dialog-required text-center'])[1]
label_PasswordMustBeAtleast 	xpath					//p[contains(@class,'password-information')]
checkBox_Signup					id						dwfrm_profile_customer_addtoemaillist
label_YouAreSigningUpToReceive	 xpath					//label[@for='dwfrm_profile_customer_addtoemaillist']
label_EnterAFirstName			xpath					//span[@class='error' and @for='dwfrm_profile_customer_firstname']
label_EnterALastName			xpath					//span[@class='error' and @for='dwfrm_profile_customer_lastname']
label_EnterYourEmailAddress 	xpath					//span[@class='error' and @for='dwfrm_profile_customer_email']
label_ConfirmYourEmailAddress	 xpath   				//span[@class='error' and @for='dwfrm_profile_customer_emailconfirm']
label_EnterYourPassword			xpath					//span[@class='error' and @for='dwfrm_profile_login_password']
label_ConfirmYourPassword		xpath					//span[@class='error' and @for='dwfrm_profile_login_passwordconfirm']
label_EmailAlreadyRegistered 	 xpath					//span[@class='form-caption error-message']
linkText_ForgotPassword			 xpath					(//form[@id='dwfrm_login']//a[@id='password-reset'])[1]
textBox_PasswordRequest		    id 						dwfrm_requestpassword_email
button_SubmitForgotPassword		xpath					//form[@id='PasswordResetForm']//button
label_PasswordRequest			xpath					//h4[text()='Password Request']
linkText_SignInAgain			classname				sign-in-again
label_EmailsDoNotMatch				xpath				//span[@class='error' and text()='Emails do not match']
label_YourPasswordMustBeEight		xpath				//span[@class='error' and text()='Your password must be 8 characters long']
label_PasswordsDoNotMatch			xpath				//span[@class='error' and text()='Passwords do not match']
box_primaryCreditCard				classname				primary
linkText_EditLinkForCreditCard		xpath				//a[contains(text(),"Edit")]
checkbox_MakePrimaryPayment			id					dwfrm_paymentinstruments_creditcards_newcreditcard_isPrimaryCreditCard
button_confirm_email             xpath               //input[@id='dwfrm_billing_billingAddress_email_emailconfirm']
continue            			xpath						//button[contains(text(),'Continue')]
 dropdown_Newcard_month        xpath                (//button[@class='btn dropdown-toggle selectpicker btn-default'])[4]
 text_Newcard_mnth             xpath              (//a[@class='select-option']//span[@class='text' and text()='01'])[2]
 dropdown_Newcard_year         xpath                   (//button[@class='btn dropdown-toggle selectpicker btn-default'])[5]
  text_Newcard_year             xpath                   (//a[@class='select-option']//span[@class='text' and text()='2020'])[2]
  btn_conform_card_delete        xpath                  //a[@class="button-text delete icon-coach-close-grey"][1]
  icon_conform_delete          xpath                  //button[@class='btn danger']
burger_icon                    css                   .burger.icm-icon-burger
button_signin                  xpath                    (//button[@class='btn btn-default signin'])[2]
button_Save_Address			   css 					  .apply-button.btn.btn-default.save-btn
button_account                 css                   #account-dropdown